language: node_js
node_js:
  - "8"
before_script:
  - chmod 0777 ./node_modules/.bin/mocha
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm install -g webdriver-manager
  - webdriver-manager update
  - webdriver-manager start &
  - sleep 3
addons:
  firefox: "58"
