language: node_js
node_js:
  - "8"
before_script:
  - chmod 0777 ./node_modules/.bin/mocha
  - "wget http://selenium-release.storage.googleapis.com/3.9/selenium-server-standalone-3.9.0.jar"
  - "java -jar selenium-server-standalone-3.9.0.jar > /dev/null &"
  - sleep 3
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm install -g eslint gulp eslint-plugin-react webpack"
addons:
  firefox: "58"
